### ISSUE TITLE
if github habit already synced, do not still show button for tracking github

### ISSUE THREAD

**Issue by awortham** [ianderse/feed_engine#58]

**Comment by ianderse** [comment]
Disagree with this, you should have the ability to track multiple repos

**Comment by awortham** [comment]
Ah, I thought it was to put in your github account, not a specific repo. so it didn't make sense to have multiple of my account. 
That makes much more sense to track specific repos. 
It doesn't error out if I tell it to track my account name 'awortham'. maybe we should provide some instructions for people to track 'username/reponame' and perhaps make it error out if they only provide the username?

I'm not sure what you had in mind. It just didn't seem clear to me what I was supposed to do
